# Usamos una imagen de Python ligera
FROM python:3.10-slim

# Evita que Python genere archivos .pyc y permite ver logs en tiempo real
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Instalamos dependencias del sistema necesarias (importante para FAISS)
RUN apt-get update && apt-get install -y \
    libgomp1 \
    libopenblas-dev \
    libomp-dev \
    && rm -rf /var/lib/apt/lists/*

# Establecemos el directorio de trabajo
WORKDIR /app

# Copiamos el archivo de dependencias e instalamos [cite: 2]
COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade pip setuptools wheel
RUN pip install --no-cache-dir -r requirements.txt

# Copiamos todo el contenido de la carpeta actual al contenedor
COPY . .

# Exponemos el puerto [cite: 3]
EXPOSE 8000

# Comando para arrancar el servidor
CMD ["uvicorn", "APIPython:app", "--host", "0.0.0.0", "--port", "8000"]