services:
  api_aigerim:
    build: ./TFGPython
    container_name: aigerim_server
    ports:
      - "8000:8000"
    volumes:
      - ./TFGPython/BasesDeDatos:/app/BasesDeDatos
      - ./TFGPython/characters:/app/characters
      - ./UploadedFiles:/UploadedFiles  # Para que el contenedor vea los archivos de Unity
    restart: always