services:
  api_aigerim:
    build: .
    container_name: aigerim_server
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./BasesDeDatos:/app/BasesDeDatos
    restart: always